#+TITLE: TL Doom Emacs Config
#+PROPERTY: header-args :tangle config.el

* Doom Emacs Config
Doom Emacs is a distrobution of GNU Emacs that brings speed improvements and ease of use to the table which are things GNU Emacs lacks.

Official Documentation: https://github.com/hlissner/doom-emacs/blob/develop/docs/index.org

* Fonts
Sets the font and changes a few settings for visual improvements.

#+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
(setq global-prettify-symbols-mode t)
#+end_src

* Theme
Sets the theme.

#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src

* Line Numbers
Enables line numbers.

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

* Elcord
Elcord is a plugin that enables Discord rich presence for Emacs.

#+begin_src emacs-lisp
(require 'elcord)
(setq elcord-mode t)
#+end_src

* Word Wrap
Enables Word Wrap.

#+begin_src emacs-lisp
(+word-wrap-mode)
#+end_src

* Rust
Enables rust-mode when editing a *.rs file.

#+begin_src emacs-lisp
(after! rustic
  (setq rustic-lsp-server 'rust-analyzer))
#+end_src

* Org
Sets settings for org-mode such as the directory, the org-agenda file, the journal directory, etc.

#+begin_src emacs-lisp
(after! org
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
  (setq org-directory "~/Org/"
        org-agenda-files '("~/Org/agenda.org")
        org-default-notes-file (expand-file-name "notes.org" org-directory)
        org-ellipsis " ▼ "
        org-log-done 'time
        org-journal-dir "~/Org/journal/"
        org-journal-date-format "%B %d, %Y (%A) "
        org-journal-file-format "%Y-%m-%d.org"
        org-hide-emphasis-markers t
        org-link-abbrev-alist
          '(("google" . "http://www.google.com/search?q=")
            ("arch-wiki" . "https://wiki.archlinux.org/index.php/")
            ("ddg" . "https://duckduckgo.com/?q=")
            ("wiki" . "https://en.wikipedia.org/wiki/"))))
#+end_src

* Dired
Some options for the built-in file manager.

#+begin_src emacs-lisp
(evil-define-key 'normal dired-mode-map
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-open-file)
(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
(setq dired-open-extensions '(("gif" . "sxiv")
                              ("jpg" . "sxiv")
                              ("png" . "sxiv")
                              ("mkv" . "mpv")
                              ("mp4" . "mpv")))
#+end_src

* mu4e
Enables mu4e. My emails are contained in a seperate file for privacy reasons.

#+begin_src emacs-lisp
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
(load "~/.config/doom/email")
(defun my-mu4e-set-account ()
  "Set the account for composing a message."
  (let* ((account
          (if mu4e-compose-parent-message
              (let ((maildir (mu4e-message-field mu4e-compose-parent-message :maildir)))
                (string-match "/\\(.*?\\)/" maildir)
                (match-string 1 maildir))
            (completing-read (format "Compose with account: (%s) "
                                     (mapconcat #'(lambda (var) (car var))
                                                my-mu4e-account-alist "/"))
                             (mapcar #'(lambda (var) (car var)) my-mu4e-account-alist)
                             nil t nil nil (caar my-mu4e-account-alist))))
         (account-vars (cdr (assoc account my-mu4e-account-alist))))
    (if account-vars
        (mapc #'(lambda (var)
                  (set (car var) (cadr var)))
              account-vars)
      (error "No email account found"))))

(add-hook 'mu4e-compose-pre-hook 'my-mu4e-set-account)
#+end_src

* Emojis
Enables emoji support.

#+begin_src emacs-lisp
(use-package emojify
  :hook (after-init . global-emojify-mode))
#+end_src
