name: xmonad-config
synopsis: My config for XMonad and XMobar
description: My config for XMonad and XMobar
author: Trey Lewis <tldesktopenvironment@gmail.com>
git: https://gitlab.com/SuperMrDoggyDog/dotfiles
category: Configuration

dependencies:
  - base
  - xmonad >= 0.17.0
  - xmonad-contrib >= 0.17.0
  - xmobar >= 0.40
    
library:
  source-dirs: .
