# Don't print a new line at the start of the prompt
add_newline = false

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Disables outputing of command duration time
[cmd_duration]
disabled = true

# Shows the username always
[username]
show_always = true
format = "[$user](26)"

# Shows the hostname always
[hostname]
ssh_only = false
format = "[@$hostname](7) "

# Disables the package module
[package]
disabled = true

# Language Options
[rust]
format = "via [Rust $symbol($version)]($style) "
symbol = " "

[dart]
format = "via [Dart $symbol($version)]($style) "
symbol = " "

[shell]
disabled = false
bash_indicator = "[](3)"
fish_indicator = "[](3)"

[directory]
truncate_to_repo = false
home_symbol = "~"
read_only = ""
